### ISSUE TITLE
Gangster，I think it's a bug

### ISSUE THREAD

**Issue by Cavy666** [greatclock/excel_to_scriptableobject#1]
If i don't select "Generate ToString Method", "}" is Missing ! 
line 906
if (!string.IsNullOrEmpty(excel.name_space)) {
	content.AppendLine("}");
}
change to 
if (!string.IsNullOrEmpty(excel.name_space)) {
	content.AppendLine("	}");
	content.AppendLine("}");
}
else
{
	content.AppendLine("}");
}
it's done

**Comment by greatclock** [comment]
My fault, thx!
