### ISSUE TITLE
Couldn't read the sample excel file...

### ISSUE THREAD

**Issue by workshop201** [greatclock/excel_to_scriptableobject#3]
I am using unity version 2022.3.9f1, and installed from package manager using git URL.  I couldn't successfully read the sample excel file. It said; 

"Fail to read 'Excels/StudentsData.xlsx'. It seems that it's not a proper xlsx file..."

The xlsx file seems okay with my Excel (Excel 2019 ver 2312 build 16.0.17126.20132).
Since some old excel compatible libraries don't support xlsx. so I saved the excel file as old xls format, then it said 

"Fail to parse 'Excels/StudentsData.xls' because of invalid field name '"

![image](https://github.com/greatclock/excel_to_scriptableobject/assets/33928477/7d42e198-9e06-4ef7-a377-53c70d47eb37)

Also, it will be great if we have 'refresh folder structure' button somewhere, since the folder list seems to show the folder structure when the library is loaded, which can be often outdated when users change the folder structure. ;)

**Comment by greatclock** [comment]
Thank you for your support !

It is 'Excel.dll' that converts .xlsx into DataSet. It's said that the 'Excel.dll' supports .xls, but I've never successfully read .xls even once.

.xlsx saved from some online document solution may not work in my experience.

So I should know where is your 'StudentsData.xlsx' is exported from. If it's not from Micorsoft Excel, 'Save as' in Excel.

Or you can trace the 'ExceptionMessage' of variable named 'reader' just before (ExcelToScriptableObject:74) when variable 'data' is null.

Looking forward to your good news ~

**Comment by workshop201** [comment]
> Thank you for your support !
> 
> It is 'Excel.dll' that converts .xlsx into DataSet. It's said that the 'Excel.dll' supports .xls, but I've never successfully read .xls even once.
> 
> .xlsx saved from some online document solution may not work in my experience.
> 
> So I should know where is your 'StudentsData.xlsx' is exported from. If it's not from Micorsoft Excel, 'Save as' in Excel.
> 
> Or you can trace the 'ExceptionMessage' of variable named 'reader' just before (ExcelToScriptableObject:74) when variable 'data' is null.
> 
> Looking forward to your good news ~

Thank you very much for the prompt reply.  I created a completely new empty project and tried the same thing and this time I got 

"Fail to parse 'Excels/StudentsData.xlsx' because of invalid field types 'eGender, eRelationship'..."

Since the bundled ExcelExample.xlsx do have eGender or eRelationship fields, I believe the code itself works well in the empty project. However when I do the same thing in my existing project, it showed the error I mentioned in the previous post. So this issue seems to come from my code. ;) I am sorry for bothering you. 

Anyway for your information, my settings are as below;

The StudentsData.xlsx is located at /[ProjectRoot]/Excels, which is at the same level as /[ProjectRoot]/Assets. 
Both of output folders are targeted to /[ProjectRoot]/Assets/BasicData, but they are registered as 'Assets/BasicData', as you might guess. 

![image](https://github.com/greatclock/excel_to_scriptableobject/assets/33928477/1a47cc3a-eb2b-4311-85a4-235954f45052)

Oh there is one request. The file browser dialogs seem to store the folder path for entire PC. So if I open multiple projects using this library simultaneoulsy, I need to switch folder path from one project to another project again and again. If the folder information is stored for each project, I believe this can improve UX. :) Or maybe you can let users specify the project root path for each project. 

Thank you, and have a great day!

**Comment by greatclock** [comment]
All the configurations are stored in [ProjectRoot]/ProjectSettings/ExcelToScriptableObjectSettings.asset. You can open it and edit it manually using any of your text editor. It is a pure json file.

If the .xlsx files are stored in any folder under your [ProjectRoot], relative path is used in ExcelToScriptableObjectSettings.asset.
